import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/componets/Navbar";
import QueryProvider from "@/componets/QueryProvider";
import { Toaster } from "react-hot-toast";
import NavbarWrapper from "@/componets/HideNavbar";
import ThemeProvider from "@/componets/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uz">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100 transition-colors`}
      >
        <ThemeProvider>
          <QueryProvider>
            <NavbarWrapper/>
            <Toaster/>
            {children}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
